CC = gcc
CFLAGS = -std=c99 -Wall -Werror -pedantic -g

CXX=g++
CXXFLAGS="-std=c++17 -Wall -Werror -pedantic -g"

Factorial: factorial.c
	${CC} ${CFLAGS} -o $@ $^

Hello: hello.c
	${CC} ${CFLAGS} -o $@ $^
